### PR TITLE
Fix issue No: 2605

### LINKED ISSUE #2605: Ordering issue in the client connector
Release - 0.9

**Steps**
1. Add a service
2. Add a HTTP client connector

**Issue**
The endpoint will be added at the bottom by default, so the reply statement is at top

endpoint

### PR DESCRIPTION
**Pull request by nadeeshaan**
Resolves #2605

### CODE REVIEW

File: modules/web/js/ballerina/components/panel-decorator.jsx [hunk 1]
```diff
@@ -298,18 +298,36 @@ class PanelDecorator extends React.Component {
...
 
     onDropZoneActivate(e) {
-        const dragDropManager = this.context.dragDropManager,
-            dropTarget = this.props.dropTarget,
-            dropSourceValidateCB = this.props.dropSourceValidateCB;
+        const dragDropManager = this.context.dragDropManager;
+        const dropTarget = this.props.dropTarget;
+        const dropSourceValidateCB = this.props.dropSourceValidateCB;
+        const droppedNodeIndexCallBack = function () {
+            if (BallerinaASTFactory.isConnectorDeclaration(dragDropManager.getNodeBeingDragged())) {
```
Comment (hemikak) [inline modules/web/js/ballerina/components/panel-decorator.jsx]: Cant we move the logic to ConnectorDeclaration ast implementation ?

Comment (nadeeshaan) [inline modules/web/js/ballerina/components/panel-decorator.jsx]: Here the consideration was, that the panel is the one who should decide which should be the index. Connector declaration should not position himself because based on the drop zone it is being positioned. WDYT?
