### PR TITLE
Connector scoping for block statements and workers

### LINKED ISSUE #2645: The life-line of the connector is not drawn when the creation is done inside a try-catch
Release - 0.91.1 (31/07)

**Steps**
1. Add a try catch block
2. Create a http or sql client connection

**Issue**
The life-line is not created and the composer crashes when switch to the source view

aa

### LINKED ISSUE #2654: The life-line of the connector is not drawn when the creation is done inside a transaction block
Release - 0.91

**Steps**
1. Add the below code from the source view and check the design view

```
function Function1 () {
    transaction {
        map props = {"jdbcUrl": "jdbc:mysql://localhost:3306/db", "username": "root", "password": "root"};
        sql:ClientConnector testDB = create sql:ClientConnector (props);
        sql:Parameter[] parameters = [];
        int count = sql:ClientConnector.update(testDB, "Insert into Customers(id,name) value (1, 'Anne')", parameters);
        } aborted {
    } committed {
    }
}
```

**Issue**
The connector life-line is not created

### LINKED ISSUE #2658: The life-line of the connector is not drawn when the creation is done inside fork-join/worker
Release - 0.91

**Steps**
1. Add the below code in a worker inside a worker from the design view

```
       sql:ClientConnector testDB = create sql:ClientConnector (props);
```

**Issue**
The connector life-line is not created

### LINKED ISSUE #2670: Issues in the join block of fork-join
join

### LINKED ISSUE #2672: Connectors cannot be added in the fork block in fork-join
Release 0.91.1

Connectors should be able to be added in a fork join block to interact with the workers. Currently cannot add connectors inside the fork block. If the code is done from the source view and switch to the design view, nothing will be drawn.

```
        fork {

            worker AirlineWorker {

                http:ClientConnector airline = create http:ClientConnector("http://localhost:9090/airline");
                response = http:ClientConnector.post(airline, "/book/" + country, m);
                system:println(response);

                system:println("constant value is " + index);
                system:println("Message sent from the airline worker");
                response -> fork;

            }

            worker HotelWorker {

                http:ClientConnector hotel = create http:ClientConnector("http://localhost:9090/hotel");
                response = http:ClientConnector.post(hotel, "/book/" + country, m);
                system:println(response);

                system:println("constant value is " + index);
                system:println("Message sent from the hotel worker");
                msg, i -> fork;

            }

        } join (all) (map test) {

        }

```

### LINKED ISSUE #2677: Action invocation expressions declared in one worker can be connected to connectors in other workers
An action invocation expression declared in a worker can only be connected to connectors declared in that worker's scope.
connectorarrow

### PR DESCRIPTION
**Pull request by NatashaWso2**
Fixes #2672
Fixes #2645
Fixes #2654
Fixes #2658
Fixes #2677 
Fixes #2670

### CODE REVIEW

File: modules/web/js/ballerina/ast/statements/statement.js [hunk 1]
```diff
@@ -49,6 +49,60 @@ class Statement extends ASTNode {
     getStatementString() {
         throw new Error('This method should be implemented by sub class');
     }
+
+
+    /**
```
Comment (keizer619) [inline modules/web/js/ballerina/ast/statements/statement.js]: @NatashaWso2 
You could include parameter type as @param {string} connectorName <description>
and returns type as @returns {object} <description>

File: modules/web/js/ballerina/ast/statements/transaction-statement.js [hunk 2]
```diff
@@ -44,8 +44,14 @@ class TransactionStatement extends Statement {
      * */
     initFromJson(jsonNode) {
         const self = this;
+        let child;
         _.each(jsonNode.children, (childNode) => {
-            const child = self.getFactory().createFromJson(childNode);
+            if (childNode.type === 'variable_definition_statement' &&
```
Comment (keizer619) [inline modules/web/js/ballerina/ast/statements/transaction-statement.js]: @NatashaWso2 
Checking node could be improved with AST factory functions
```
BallerinaASTFactory.isVariableDefinitionStatement()
BallerinaASTFactory.isConnectorInitExpression()
```

**Comment by NatashaWso2** [comment]
Fixes: https://github.com/ballerinalang/composer/issues/2672
Fixes: https://github.com/ballerinalang/composer/issues/2645
Fixes: https://github.com/ballerinalang/composer/issues/2654
Fixes: https://github.com/ballerinalang/composer/issues/2658
