### PR TITLE
Fix the issue with expression editor throw an error on removal of semicolon

### LINKED ISSUE #4340: Error message pops up on expression editor update
"Invalid content provided" error message pops up on expression editor update and edited text is not updated in the source code.

screen shot 2017-11-02 at 8 52 51 am

### PR DESCRIPTION
**Pull request by NipunaMarcus**
Fix #4340

### CODE REVIEW

File: modules/web/js/ballerina/model/tree-util.js [hunk 1]
```diff
@@ -408,6 +408,10 @@ class TreeUtil extends AbstractTreeUtil {
             // Get the parent node.
             const expressionParentNode = node.parent;
 
+            source = source.substr(source.length - 1) === ';'
```
Comment (hemikak) [inline modules/web/js/ballerina/model/tree-util.js]: We can use endsWith function here.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith

File: modules/web/js/expression-editor/expression-editor-utils.js [hunk 2]
```diff
@@ -49,9 +49,13 @@ class ExpressionEditor {
         this.ballerinaFileEditor = ballerinaFileEditor;
 
         // Get the expression for the statement or expression.
-        const expression = props.getterMethod instanceof Function ? props.getterMethod.call() :
+        let expression = props.getterMethod instanceof Function ? props.getterMethod.call() :
             (_.isNil(props.model.getSource()) ? '' : props.model.getSource(true).replace(/(?:\r\n|\r|\n)/g, ' '));
 
+        expression = expression.substr(expression.length - 1) === ';'
```
Comment (hemikak) [inline modules/web/js/expression-editor/expression-editor-utils.js]: We can use endsWith function here.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith
