### PR TITLE
Fix Issue 2298

### LINKED ISSUE #2298: "Error in BLang parser rest service for composer" when reply an element of a message type array
It works when the line 33 is removed
nullcomposer

### PR DESCRIPTION
**Pull request by nadeeshaan**
Resolves #2298

### CODE REVIEW

File: modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangExpressionModelBuilder.java [hunk 1]
```diff
@@ -699,7 +699,20 @@ public void visit(FieldBasedVarRefExpr fieldBasedVarRefExpr) {
 
     @Override
     public void visit(IndexBasedVarRefExpr indexBasedVarRefExpr) {
-
+        StringBuffer buffer = new StringBuffer();
```
Comment (hemikak) [inline modules/services/workspace-service/src/main/java/org/ballerinalang/composer/service/workspace/rest/datamodel/BLangExpressionModelBuilder.java]: We should use StringBuilder as StringBuffer is old.
